### ISSUE TITLE
WA DOH changed their reporting format

### ISSUE THREAD

**Issue by rainiernate** [jake-low/covid-19-wa-data#1]
Check out the DOH website. As of 9pm they updated numbers and the format of the reporting. You have to find the data from here now. Unfortunately this has caused the data for 3/29 to post incorrectly for a lot of the scraping services downstream.

<img width="802" alt="Screen Shot 2020-03-29 at 9 06 49 PM" src="https://user-images.githubusercontent.com/13302862/77876271-56833b80-7207-11ea-95ba-ec0bc9a16a93.png">

**Comment by jake-low** [comment]
Thank you for the report. I'm aware of the problem but don't have a good fix. For now I've resorted to transcribing the tables from the DOH website manually. Data isn't available from them for the last three days as they've been having some kind of technical problems, but the 3/28 data they published in the new format is available in this repository now. I'll try to keep up with new publications (transcribing manually) for now.
